name: Librejo Front CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'packages/librejo-front/**'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        package: [librejo-front]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install, lint, and test
        run: |
          yarn --pure-lockfile
          npx lerna bootstrap --scope ${{ matrix.package }}
          npx lerna exec --scope ${{ matrix.package }} -- yarn lint
          npx lerna exec --scope ${{ matrix.package }} -- yarn test

      - name: SonarCloud Scan
        uses: romainbellande/sonarcloud-github-action@more-options
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/${{ matrix.package }}
          organization: naimor
          sources: .
          projectKey: kune:librejo
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src
