name: Librejo API Deploy CI

on:
  push:
    branches:
      - master
    paths:
      - 'packages/librejo-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_LIBREJO_API_APP_NAME }} # you aplication name
          dockerfile: './packages/librejo-api' # set the path to the folder wher the Dokerfile is located
